import '@sass/globals.css'

import { Inter } from 'next/font/google'

import type { LayoutProps } from '@types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Layout(props: LayoutProps) {
  const { children } = props

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default Layout
